stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw/sensor_data.csv

  data_cleaning:
    cmd: python src/clean_data.py
    deps:
      - src/clean_data.py
      - src/clean_data.sql
      - data/raw/sensor_data.csv
    outs:
      - data/processed/cleaned_data.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - src/feature_engineering.sql
      - data/processed/cleaned_data.csv
    outs:
      - data/processed/sensor_features.csv

  train_model:
    cmd: python src/train_model.py
    deps:
      - src/train_model.py
      - data/processed/sensor_features.csv
    outs:
      - models/model.pkl
      - models/scaler.pkl
    params:
      - model

  evaluate_model:
    cmd: python src/evaluate_model.py
    deps:
      - src/evaluate_model.py
      - models/model.pkl
      - models/scaler.pkl
      - data/processed/sensor_features.csv
    outs:
      - metrics.json
    params:
      - data

  deploy_model:
    cmd: |
      docker build -t predictive-maintenance-app .
      docker run -p 5000:5000 predictive-maintenance-app
    deps:
      - Dockerfile
      - src/app.py
      - models/model.pkl
      - models/scaler.pkl
    outs:
      - docker_image: predictive-maintenance-app
