model:
  type: RandomForest
  random_state: 42
  max_depth: 10
  n_estimators: 100
  min_samples_split: 2
  min_samples_leaf: 1
  bootstrap: True

data:
  aws_rds:
    host: "rds_endpoint"
    user: "username"
    password: "password"
    dbname: "dbname"
    port: 5432
  paths:
    raw_data: "data/raw/sensor_data.csv"
    cleaned_data: "data/processed/cleaned_data.csv"
    features: "data/processed/sensor_features.csv"
    test_data: "data/processed/sensor_test.csv"
